# Generated by Django 4.0.5 on 2022-06-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
